demo/urls.py
from django.contrib import admin
from django.urls import path, include
from demo.settings import MEDIA_ROOT
from giox.urls import giox_home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', giox_home, name="giox_home"),
    path("giox", include(("giox.urls", "giox"), namespace="giox")),
    path("account", include(("account.urls", "account"), namespace="account")),
    path("my_pasionate", include(("my_pasionate.urls", "my_pasionate"), namespace="my_pasionate")),
    path("posts", include(("posts.urls", "posts"), namespace="posts")),
    path("videos", include(("videos.urls", "videos"), namespace="videos")),
    path("embed_video", include(("embed_video.urls", "embed_video"), namespace="embed_video")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

my_pasionate/urls.py
from django.urls import path
from my_pasionate.views import(
     my_pasio,
     create_question_answer,
     get_question_answer,
     fedo,
     )


urlpatterns =[
    path("", my_pasio, name="my_pasio"),
    path("create_question_answer", create_question_answer, name="create_question_answer"),
    path("get_question_answer", get_question_answer, name="get_question_answer"),
    path("fedo", fedo, name="fedo")
]

urls.py
from django.urls import path
from giox.views import( 
    giox_home,
    create_blogPost,
    getBlogPost,
    BlogPostView,
    )


urlpatterns=[
    path(" ", giox_home, name="giox_home"),
    path("BlogPostView", BlogPostView.as_view()),
    path("create_blogPost", create_blogPost, name="create_blogPost"),
    path("getBlogPost", getBlogPost, name="getBlogPost"),
]

my_pasionate/models.py
from django.db import models

# Create your models here.
PRIORITY = [
    ("L", "low"),
    ("M", "medium"),
    ("H", "high"),
]


class QuestionAnswer(models.Model):
    title = models.CharField(max_length=60)
    question = models.TextField(max_length=400)
    answer = models.TextField(max_length=300)
    priority = models.CharField(max_length=1, choices=PRIORITY)

    class Meta:
        verbose_name = "The Question, The Answer"
        verbose_name_plural = "User Questions, User Answers"

    def __str__(self):
        return self.title

my_pasionate/forms.py
from django.contrib.auth.forms import forms
from django.template.defaultfilters import title

from .models import QuestionAnswer


class QuestionAnswerForm(forms.Form):
    class Meta:
        model = QuestionAnswer
        fields = ["title", "question", "answer", "priority"]
        widgets = {title: forms.TextInput(attrs={"class": "form-control"})}

    def save(self):
        pass


class CreateQuestionAnswerForm(forms.ModelForm):
    class Meta:
        model = QuestionAnswer
        fields = ["title", "question", "answer", "priority"]

my_pasionate/views.py
from django.shortcuts import render, redirect
from.models import QuestionAnswer
from .forms import CreateQuestionAnswerForm, QuestionAnswerForm
from django.http import JsonResponse, HttpResponse
# Create your views here.

def my_pasio(request):
    questions = QuestionAnswer.objects.all()
    context={'questions':questions}
    return render(request, 'my_pasionate/my_pasio.html', context)

def fedo(request):
    return render(request, 'fedo.html')

"""def question_answer(request):
    if request.method == "POST":
        form = QuestionAnswerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("authy:question_answer_list")
    else:
        form = QuestionAnswerForm()
        return render(request, "question_answer.html", {"form": form})"""
    

  
def create_question_answer(request):
    form = CreateQuestionAnswerForm()

    if request.method == "POST":
        form = CreateQuestionAnswerForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("<em>New Question was created succesfully<em>")
        
    return render(request, "my_pasionate/create_question_answer.html", {"form": form})
  

def get_question_answer(request):
    questions = QuestionAnswer.objects.all()
    return JsonResponse({"questions": list(questions.values())})

my_pasionate/templates/my_pasionate/DEVO.html
<!DOCTYPE html>
<img src=""/>
<html>
    
</html>

my_pasionate/templates/my_pasionate/create_question_answer.html
{% extends 'base.html' %}
{% load static %}

{% block title %}QuestionAnswerForm{% endblock title%}

{% block content %}
<div class= "content-align-centre"><h2>CreationForm</h2>
<div class= "bl-p-f">
<form   method="POST" id="creation-form"  enctype="multipart/form-data">
  
  {% csrf_token %}
   {{form}}
  <button type="submit">CreationForm</button> 
  </form>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
			  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
			  crossorigin="anonymous">
  $(document).on('submit', '#creation-form', function(){
       e.preventDefault();
        $.ajax({
          type:'POST',
          url: "{% url 'my_pasionate:create_question_answer' %}",
          data:{
          title:$('#title').val(),
          question:$('#question').val(),
          answer:$('#answer').val(),
          priority:$('#priority').val(),
          csrfmiddlewaretoken:$('input[title=csrfmiddleware token]').val(),
        },
        success:function(data){
           alert(data);
        }
      });
  });
  
</script>
  
{% endblock content %}

my_pasionate/templates/my_pasionate/fedo.html

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="HTF-8">
        <meta name="viewport" content="width=device-width initial-scale=0.1">
        <title>Loading Animation</title>
        <script  type="text/javscript" src="scipt.js"></script>
        <link ref="stylesheet" href="style.css">
        <style>
            .loading{
                display: flex ;
                align-self: frex-center;
               height: 150px; 
               width: 150px;
               border:6px solid aqua;
               border-radius: 4px;
               box-shadow: 0 0 8px aqua, 0 0 8px aqua inset;
               position: center;
               top:50%;
               left:50px;
               translate: 50%, 50%;
               z-index: 10;
               animation: 2s loading ease-in-out normal;
            }
            @keyframes loading{
                0%{
                    transform: rotateX(0) rotateY(0) rotateZ(0);

                }
                33%{
                    transform:rotateX(180deg) rotateY(0) rotateZ(0);

                }
                67%{
                    transform: rotateX(180deg) rotateY(180deg) rotateZ(180deg);

                }
                100%{
                    transform: rotateX(180deg) rotateY(180deg) rotateZ('angle');
                }

            }
        </style>
    </head>
    <body>
       
        <div class="loading"></div>
       
        
    </body>

</html>

my_pasionate/templates/my_pasionate/get_question_answer.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>List of Live Data</h1>
<ul id="display-data">

</ul>



<script>
    $(document).ready(function() {
        SetInterval(function(){
          $.ajax({
            type:'GET',
            url:"{% url 'get_question_answer' %}",
            success:function(response){
                 console.log(response);
                 $('#display').empty();
                for(var key in response. Questions){
                var loop ,list ='<h2><li>' + response(Questions[key].name) + '</li></h2>'
                $("#display").append(temp);
            };
            error:function$(response);{
              
              alert("An Error Occurred")
            };
        },
    },1000);

  });




});

</script>

{% endblock %}

my_pasionate/templates/my_pasionate/my.html
{% load static %}
<!DOCTYPE html>
<html lang="utf-8">
<head>
    <meta name="viewport" content="width=device-width initial-scale=1.0"/>
    <link ref="stylesheet" type="style/css"/>
    <title>Creating aA Website</title>
    <style>
        .parent{
            padding: 20px;
            display: grid;
            grid-template-columns:1fr 1fr 1fr;
            row-gap:20px;
            column-gap: 20px; 
        }
        .item:nth-child(1){
            font-size: 1.1rem;
            grid-row: span 2;
            display: grid;
            align-content: center;
        }
        .item{
            background-color: rgb(228,228,228);
            padding: 20px;
            font-size:0.77rem;
            line-height: 1.7;
        }
        .item p {
            margin:0;
        }
        .example-banner{
            max-width: 900px;
            height: 300px;
            background-color: rgb(255, 222, 234);
            margin:0 auto 24px auto;
            display: grid;
        }
        .center{
            margin: auto;
            color: rgb(113, 113, 175);
            font-size: 3rem;
        }
        .nav-bar{
            width: 900px;
            height: 30px;
            background-color: rgb(0, 213, 255);
            display: grid;
           
            
        }
        .nav-item{
            color: #000;
             margin: auto;
        }
        .full-width-example{
           display: grid;
           grid-template-columns: mimax(auto, 900px);
           justify-content: center;
           background-color: burlywood;
           color: rgb(112, 86, 38 );
           line-height: 1.7;
           padding: 20px; 

        }
        .photo-example{
            display: grid;
            grid-template-columns: 1fr, 1fr, 1fr;
            grid-template-rows: 100px 170px 50px;
            max-width: 700px;
            margin: 20px auto;

        }
        .photo-example img {
            max-width: 100px;
            display: block;
        }
        .overlay-text{
            margin: 0;
            color: #fff;
            grid-column: 1/3 ;
            background-color: rgb(0, 0, 0.300);
            padding: 20px;
            font-size:0.85rem;
            line-height: 1.7;
        }
        .layout{
            display: grid;
            grid-template-columns: 1fr 2.5fr;
            grid-template-areas: 
            "header heeder"
            "sidebar main"
            "sidebar footer";
            background-color: #2d1616;
        }
        .header{
            padding: 20px;
            color: blue;
            background-color: darkcyan;
            grid-area: header;
        }
        .main{
            color: #ddd;
            padding: 20px;
            line-height: 1.7;
            grid-area: main;
            
            background-color: darkolivegreen;
        }
        .sidebar{
            grid-area: sidebar;
            font-size: 0.8rem;
            color: #999;
            padding: 20px;
            background-color: brown;
        }
        .footer{
            grid-area: footer;
            color: #fff;
            padding: 15px;
            background-color: cornflowerblue;

        }
        .responsive-example{
            max-width: 1100px;
            margin: 20px auto;
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 20px;
            
            
        }
        .responsive-item{
            background-color: rgb(200, 230, 27);
            padding: 20px;
            color:rgb(90,145,123);
            line-height: 1.7; 
            overflow:auto;
        }
        .art-banner{
            background-color: rgb(0, 80, 112);
            height: 100vh;
            display: grid;
            grid-template-columns: 20px 1fr 1fr 1fr 20px;
            grid-template-rows: 20px 1fr 1fr 1fr 20px;


        }
        .art-banner-bg{
            opacity: 0.1;
            background:url("media/bg.jpeg") center center no-repeat;
            background-size: cover;
        }
        .banner-text{
            color: #fff;
            font-size: 8vw;
            font-weight: bold;
            grid-column: 2/span 2;
            grid-row: 3;
            align-self: center;
            justify-self: center;
        }
        .badge{ 
            display: grid;
            grid-column: 4/5;
            grid-row: 3/4;
            background-color: rgb(255,41,123);
            color: #fff;
            font-size: 2.5vw;
            font-weight: bold;
            width: 10vw;
            height: 10vw;
            border-radius: 50%;
        }
        .badge p {
            margin: auto;
            
        }
        .art-banner::before{
            content: "";
            opacity: 0.85;
            border-top:5px solid rgb(255, 41, 123);
            border-right: 5px solid rgb(255,41, 123);
            grid-column: 4;
            grid-row: 2 /span 2;

        }
        .art-banner::after{
            content:"";
            opacity: 0.85;
            border-bottom: 5px solid rgb(255, 41, 123);
            border-left: 5px solid rgb(255, 41, 123);
            grid-column: 2;
            grid-row: 3 /span 2;
        }




            
            
        
            
            
        

    </style>

</head>
<body>
    <div class="nav-bar">
        <nav class="nav-item">
            my project
        </nav>
        
    </div>
    <div class="parent">
        <div class="item">
            <h1>Main Column</h1>
            <p>Creating a Website to teach Federalism is a large an complex
                , and can be broken into smaller manageble parts.
               It invove several stages from Planning to Designing, development,
               and Deployement.
            </p>
            <h2>Key Parts Of a Webapp</h2>
        </div>
        <div class="item" >
           <p>To make the idea more imagenable,
            
                Back-end or Serve-side using Technologies eg Django to 
                    developthe back-end Responsibilities
                User Authentication and management which involves Signup, 
                    Login and Roles like Students and Teachers
                Content Management Like Quiz QnA and Othe Topics of 
                    Educational Resource   
         </p> 
        </div>
        <div class="item">
            <p> Front-End
                Technologies Framework like React.js,Or 
                        Plain HTMl/CSS/JS  
            </p>
        </div>
        <div class="item">
           <p>Responsible for Creating
            
                A User Friendly Interface
                Navigation through Lessons, Quiz
                    and Othe Teaching Modules
                Interactive Tools of Diagrams, Maps of
                Federal gorvenment systems
           </p>
        </div>
        <div class="item" >
            <p> Database
                
                    Using Technologies like Postgreql,Mysql,SQLite
                        Pre-integrated with Django
                    
                    Used to store User' information
                    Educational content, Quiz Results   
            </p>
        </div>
        <div class="item" >
            <p>Features
                
                    Federalism Knowledge based
                    Definition
                    Principles lik Autonomy and Shared power
                    Quiz an Tests
                    Interactive Maps, diagrams representing Fedralism
                    Progress tracker to moniter User' achievements
            </p>
        </div>
        

    </div>
    <div class="example-banner">
        <div class="center">
            Hello
            </div>
    </div>
    <div class="full-width-example">
        <h2>development Steps</h2>
        <p>Define Requirements & Scope</p>
        <p>What Specification Do you want To Teach About Federalism!</p>
        <p>What is your target Audience </p>

    </div>
    <div class="photo-example">
        <img src="/ demo/giox/static giox/css/images/log1.png.png/" alt="log1."/>
        <div class="overlay-text">
            <p>Design the app, Plan the user journey from registration to dashboard-lesson quiz.</p>

        </div>     
    </div>
    <div class="layout">
        <div class="header">This is the header </div>
        <div class="main">
            <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p>
            <p>Build and tie Components</p>
           
        </div>

        <div class="sidebar">
           
            <p>This sidebar  has usful links and content.</p>
            <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p>
            <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p>
            <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p>
            <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p>
            <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p>
        </div>

        <div class="footer">&copy 2021</div>

    </div>
      <div class="responsive-example" >
 
    
     <div class="responsive-item">
        <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
     <div class="responsive-item">
        <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
     
    <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
     <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
     <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
       <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
     <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
      <div class="responsive-item">
       <p>set up the framework Install django to create the back-end and connect it to the Front-end Framework e.g through django template engines</p></div>
     
    </div>
    <div class="art-banner">
        <div class="art">
       
        </div>
        <div>
         <img  class= "art-banner-bg"src="media/bg.jpeg" alt="bg"/> 
        </div>
        <div class="banner-text">
          Hello there.
        </div>
        <div class="badge"><p>New!</p> </div>
           
    </div>
</body>
</html>

my_pasionate/templates/my_pasionate/my_pasio.html
{% extends 'base.html' %}
{% load static %}
<html>
<haed>

   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <title><h1>giox home page    
{% block title %}My Pasionate Page {% endblock title %}  </h1> </title>
   
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="">
   <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/superhero/bootstrap.min.css">
   <link href="{% static 'giox/css/main.css' %}" rel="stylesheet" type="text/css">
   <link href="{% static 'giox/dashboard.css' %}" rel="styslesheet">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
 <style>
  
 </style>
</haed>
<body>
{% block content %}

 <div class="mypasio-cont">

    <div class="header-my-p">
      <p>Transformations of Questions</p>
    </div>
  <div class="mypasionate-main">
   
   <div class="graphics-examples"><h1>Title Graphic Examples</h1><hr>
    <img src="{% static '/giox/images/graphicy.png/' %}" alt="graphicy" width="100%">
    <div class="graphic-img">
    
       <div class="img1">
        <img src="{% static '/giox/images/part-ky.jpg.jpg/'%}" alt="part-ky" width="150px"height="250px">
       </div>
       <div class="img2">
        <img src="{% static '/giox/images/crowi.jpg/' %}" alt="crowi" width="150px" height="250px">
       </div>
       <div class="img3">
        <img src="{% static '/giox/images/rose.jpg/' %}" alt="rose" width="145px" height="250px" >
       </div>
       
    </div>
  
  </div>
   <div class="my_pasionate-nav">
    <h1>This Is Pasio-Navbar</h1><hr>
     <ul>
       <a class="my_pasionate-nav-a1" href="{% url 'my_pasionate:create_question_answer' %}">CreationForm</a>
       <br>
       <a class="my_pasionate-nav-a2" href="{% url 'my_pasionate:get_question_answer' %}">GET-Me-QNA</a><br>
       <a class="my_pasionate-nav-a3" href="{%  url 'my_pasionate:fedo' %}">Tempo Demo</a><br>  
     </ul><hr>
     <div class="nav-imo">
     <div class="img4" >

      <img src="{% static '/giox/images/road-to-federalism.jpg/' %}" alt="road-to-federalism"  width="200%" style="border: solid 5px brown;
      border-radius: 10px;">
       </div>
       <div class="img5" >

       <img src="{% static '/giox/images/cosmic.jpg/' %}" alt="cosmic" width="250px" height="220px" style="border: solid 5px blueviolet;
       border-radius: 10px;">
        <p> my slide</p>
       </div>
      </div>

   </div>

   <div class="in-qns">
    <h1>question-List</h1><hr>
     <ol>
         {% for question in questions %}
            {{question.title}}<br>

            {{question.question}}<br>
            {{question.answer}}<br>
            {{question.priority}}<br><hr>
          {% endfor %}  
      </ol> 

    </div>
  </div>
  <div class="mypasio-footer">
    <p>I love federalism quiz questions, they are so educative and soul reviving 
      especially for some tromatized by the brutarity , corruption of highest order,
      neptimizm,arogance of political leader who only care for their families agnaist
       their nations
    </p>
  </div>
</div>

{% endblock content %}
</body>
 <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
                    integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
                    crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
     
        <script src="" async defer></script>
</html>

my_pasionate/templates/my_pasionate/question_answer.html

<!--{% extends 'base.html' %}


{% block title %}QuestionAnswerForm{% endblock title %}
{% block content %}
    <h1> QuestionAnswer</h1>
     {% for question in questions %}
      {{title}}
      {{question}}
      {{answer}}
      {{priority}}
    {% endfor %}
     <form method="POST">
          {% csrf_token %}
          {{form.as_p}}
        <button type="submit">CreateQuestionAnswer</button>
     </form>

{% endblock %}