account/urls.py
from django.urls import path
from account.views import (
    register,
    login,
    dashboard,
    logout,
    acc_home,
    must_authenticate_view
)

urlpatterns =[
    path("", acc_home, name="acc_home"),
    path("register", register, name="register"),
    path("login", login, name="login"),
    path("dashboard", dashboard, name="dashboard"),
    path ("logout", logout, name="logout"),
    path("must_authenticate", must_authenticate_view, name="must_authenticate" ),
]

demo/urls.py
from django.contrib import admin
from django.urls import path, include
from demo.settings import MEDIA_ROOT
from giox.urls import giox_home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', giox_home, name="giox_home"),
    path("giox", include(("giox.urls", "giox"), namespace="giox")),
    path("account", include(("account.urls", "account"), namespace="account")),
    path("my_pasionate", include(("my_pasionate.urls", "my_pasionate"), namespace="my_pasionate")),
    path("posts", include(("posts.urls", "posts"), namespace="posts")),
    path("videos", include(("videos.urls", "videos"), namespace="videos")),
    path("embed_video", include(("embed_video.urls", "embed_video"), namespace="embed_video")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

embed_video/urls.py
from django.urls import path
from .views import embed_home

urlpatterns=[
    path("", embed_home, name="embed_home"),
]

my_pasionate/urls.py
from django.urls import path
from my_pasionate.views import(
     my_pasio,
     create_question_answer,
     get_question_answer,
     fedo,
     )


urlpatterns =[
    path("", my_pasio, name="my_pasio"),
    path("create_question_answer", create_question_answer, name="create_question_answer"),
    path("get_question_answer", get_question_answer, name="get_question_answer"),
    path("fedo", fedo, name="fedo")
]

posts/urls.py
from django.urls import path
from .views import (
    posts_home,
    get_Posts,
    create_posts,
)

urlpatterns=[
    path("", posts_home, name="posts_home"),
    path("get_Posts", get_Posts, name="get_Posts"),
    path("create_posts", create_posts, name="create_posts"),
]

urls.py
from django.urls import path
from giox.views import( 
    giox_home,
    create_blogPost,
    getBlogPost,
    BlogPostView,
    )


urlpatterns=[
    path(" ", giox_home, name="giox_home"),
    path("BlogPostView", BlogPostView.as_view()),
    path("create_blogPost", create_blogPost, name="create_blogPost"),
    path("getBlogPost", getBlogPost, name="getBlogPost"),
]

templates/giox/create_blogPost.html
{% extends 'base.html' %}
{% load static %}

{% block title %}blogPostForm{% endblock title%}

{% block content %}
<style type="style/css">
  .create-form{
    width: 100%;
    max-width: 100%;
    padding: 15px;
    margin: auto;
  }
  .submit-button{
    max-width: 200px;
  }

</style>


<div class="container">
   <div class="row">
      <di class="col-lg-7 offset-lg-1">
        <form class="create-form" method="POST" enctype="multipart/form-data ">
          {% csrf_token %}
            
            <!--title-->
            <div class="form-group">
              <label for="id_title">Title</label>
              <input class="form-control" method="POST" enctype="multipart/form-data" type="text" name="title" placeholder="Title" required autofocus />
            </div>

            <!--body-->
            <div class="form-group">
              <label for="body" >Content</label>
              <textarea class="form-control" rows="10" type="text" name="body" placeholder="
              Thi blog is about..." required></textarea>
            </div>

            <!--image-->
            <div class="form-group">
              <label for="id_image">Image</label>
              <input type="file" name="image" id="id_image" accept="image/*" required>
            </div>

            <!--submit btn-->
            <button  class="submit-button btn btn-lg btn-primary btn-block" type="submit">Post</button>
        </form>
      </di>
   </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
			  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
			  crossorigin="anonymous">
  $(document).on('submit', '#create-form', function(){
       e.preventDefault();
        $.ajax({
          type:'POST',
          url: "{% url 'giox:create_blogPost' %}",
          data:{
          title:$('#title').val(),
          body:$('#body').val(),
          author:$('#author').val(),
          image:$('image').val(),
          csrfmiddlewaretoken:$('input[title=csrfmiddleware token]').val(),
        },
        success:function(data){
           alert(data);
        }
      });
  });
  
</script>
  
{% endblock content %}

templates/giox/getBlogPost.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>List of Live Data</h1>
<ul id="display-data">

</ul>



<script>
    $(document).ready(function() {
        SetInterval(function(){
          $.ajax({
            type:'GET',
            url:"{% url 'giox:giox/getBlogPost' %}",
            success:function(response){
                 console.log(response);
                 $('#display').empty();
                for(var key in response. BlogPosts){
                var loop ,list ='<h2><li>' + response(BlogPosts[key].name) + '</li></h2>'
                $("#display").append(temp);
            };
            error:function$(response);{
              
              alert("An Error Occurred")
            };
        },
    },1000);

  });




});

</script>

{% endblock %}

templates/giox/giox_.html
{% extends 'base.html' %}
{% load static %}
<head>
  <titie><h1>GIOX HOME PAGE</h1></titie>
  <link rel="stylesheet" type="style/css" href="{% static 'giox/css/main.css' %}"/>
  
</head>
<body>
  <style> 
    .g-layout{
      display: flex;
    }
  
    .header{
        padding: 20px;
        color: blue;
        
       
        
    }
    .g-main{
        
            
        background-color: darkolivegreen;
    }
    .sidebar{
       background-color: blue;
    }
    .footer{
         background-color: aquamarine;
}
  </style>
  <div class="g-layout" style="display: flex;
    
      
  ">
  
  <div class="g-main" >
   
   

  </div>
  <div class="g-sidebar" >
    <p>This is Sidebar</p><em>
    <a   href="{% url 'giox:giox_home'%}">Giox Page</a><br>
     <a  href="{% url 'my_pasionate:my_pasio' %}">Pasio Page</a><br>
     <a href="{% url 'account:acc_home' %}">Account</a><br>
     <a href="{% url 'giox:create_blogPost' %}">BlogCreationPage</a><br>
     <a href="{% url 'giox:getBlogPost'%}">Get-Me-List</a><br>
    <a href="{% url 'posts:posts_home' %}">Post-Me-d</a><br>
  </em>
  <button type="menu" href="{% url 'account:acc_home' %}">Display accounts</button>
  

  </div>
  <div class="g-footer" style="background-color: blueviolet;">
    <p>&copy 2024 </p>

  </div>
     {% endblock content%}
  </div>
  

    

      
   <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
                    integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
                    crossorigin="anonymous">
   </script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
     
     <script src="{% static 'giox/css/main.js' %}"></script>
     <img src="{%  static 'img/icon-alert.svg' %}" alt="django-icon-alert.svg">
     <script src="{% static 'admin/js/main.js' %}"></script>
   </body>
   
   

templates/giox/giox_home.html
{% extends 'base.html' %}
{% load static %}


<!DOCTYPE html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><h1>giox home page</h1> </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/superhero/bootstrap.min.css">
       <link href="{% static 'giox/css/main.css' %}" rel="stylesheet" type="text/css">
       <link href="{% static 'giox/dashboard.css' %}" rel="styslesheet">
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    </head>
    <body>
        <style>
        
            
        </style>
        {% block content %}
<div class="container">
        <div class="g-header">
          <h1>This Is Giox Home Page</h1>
          
        </div>
        
        <div class="my-s">mysite</div>
        
<div class="main-container">
    <div class="main">
          <h1>Welcome to My home Page</h1><hr/>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p> <h1>dome animation-direction</h1> </p>

    </div>
       <div class=" sidebar1">
        <div class="sidebar1-h"><h1>Sidebar</h1></div>
        <a class="sidebar1-a1"   href="{% url 'giox:giox_home'%}">Giox Page</a><br>
        <a class="sidebar1-a2" href="{% url 'my_pasionate:my_pasio' %}">Pasio Page</a><br>
        <a class="sidebar1-a3"href="{% url 'account:acc_home' %}">Account</a><br>
        <a class="sidebar1-a4"href="{% url 'giox:create_blogPost' %}">BlogCreationPage</a><br>
        <a class="sidebar1-a5"href="{% url 'giox:getBlogPost'%}">Get-Me-List</a><br>
        <a class="sidebar1-a6"href="{% url 'posts:posts_home' %}">Post-Me-d</a><br>
        <a class="sidebar1-a7" href="{% url 'videos:video_home' %}">Get-me-videos</a><br>
        <a class="sidebar1-a8" href="{% url 'embed_video:embed_home' %}">embed-me</a> <br>
    </div>
       <div  class="sidebar2">
       <h1>dome animation-direction</h1>
       <img src="{% static '/giox/images/crowi.jpg/' %}" alt="crowi" />
       <img src="{% static '/giox/images/logo2.jpg/'%} " alt="logo2" />
       <img src="{% static '/giox/images/part-ky.jpg.jpg /' %}" alt="part-ky"  />
       <img src="{% static '/giox/images/pierre.jpg.jpg/' %}" alt="pierre" />
       

    </div>
</div>

     <div class="footer-f">
       <b> <p><em><h1>FEDERALISM IS THE ANSWER TO ALL PAN-AFRICAN COUTRIES!</h1></em></p></b>
    </div>
</div>
        {% endblock content%}
        <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
                    integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
                    crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
     
        <script src="" async defer></script>
    </body>
</html>