demo/urls.py
from django.contrib import admin
from django.urls import path, include
from demo.settings import MEDIA_ROOT
from giox.urls import giox_home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', giox_home, name="giox_home"),
    path("giox", include(("giox.urls", "giox"), namespace="giox")),
    path("account", include(("account.urls", "account"), namespace="account")),
    path("my_pasionate", include(("my_pasionate.urls", "my_pasionate"), namespace="my_pasionate")),
    path("posts", include(("posts.urls", "posts"), namespace="posts")),
    path("videos", include(("videos.urls", "videos"), namespace="videos")),
    path("embed_video", include(("embed_video.urls", "embed_video"), namespace="embed_video")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import (
    posts_home,
    get_Posts,
    create_posts,
)

urlpatterns=[
    path("", posts_home, name="posts_home"),
    path("get_Posts", get_Posts, name="get_Posts"),
    path("create_posts", create_posts, name="create_posts"),
]

urls.py
from django.urls import path
from giox.views import( 
    giox_home,
    create_blogPost,
    getBlogPost,
    BlogPostView,
    )


urlpatterns=[
    path(" ", giox_home, name="giox_home"),
    path("BlogPostView", BlogPostView.as_view()),
    path("create_blogPost", create_blogPost, name="create_blogPost"),
    path("getBlogPost", getBlogPost, name="getBlogPost"),
]

posts/models.py
from django.db import models
from account.models import Account
from giox.models import upload_location
# Create your models here.

class Posts(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    body = models.TextField(max_length=5000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=False, blank=False)
    liked = models.ManyToManyField(Account, blank=True)
    
    update = models.DateTimeField(auto_now=True, verbose_name="update")
    created = models.DateTimeField(auto_now_add=True, verbose_name="created")

    def __str__(self):
        return str(self.title)

posts/forms.py
from django.contrib.auth.forms import forms
from .models import Posts

class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = "__all__"


class CreatePostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = "__all__"        

posts/views.py

from django.forms import model_to_dict
from django.shortcuts import render, redirect
from.models import Posts
from.forms import CreatePostsForm
from django.http import JsonResponse, HttpResponse

from .forms import PostsForm
# Create your views here.

def posts_home(request):
    return render(request, 'posts/posts_home.html')


def get_Posts(request):
    posts = Posts.objects.all()
    return JsonResponse({'posts': list(posts.values())})

 

def create_posts(request):
    form =CreatePostsForm()

    if request.method == 'POST':
        form = CreatePostsForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponse("<em>New post was created succesfully<em>")
        
    return render(request, "posts/create_posts.html", {"form": form})


    
   
   

       
    


def hello_world_view(request):
    return JsonResponse({'text': 'hello worldx2'})

"""def my_post(request):
    form = PostsForm()

    if request.method == 'POST':
       form = PostsForm(request.POST)
       if form.is_valid():
           form.save()
           return HttpResponse("<em>New post was created successfully</em>")

    return render(request, 'my_post.html', {'form':form}) """  


           
        

posts/templates/posts/create_posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %} My post {% endblock title %}

{% block content %}
<div class="content-align-center">
    <div class="col-5 mt-5">
     <form method="post" enctype="multipart/form-data" id="post-my-form">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Post</button>
      </form>
      </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
			  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
			  crossorigin="anonymous">
    $(document).on('submit', '#post-my-form', function(){
         e.preventDefault();
            $.ajax({
              type:'POST',
              url: "{% url 'posts:create_posts' %}",
              data:{
              title:$('#title').val(),
              body:$('#body').val(),
              image:$('#image').val(),
              update:$('#update').val(),
              created:$('#created').val(),
              csrfmiddlewaretoken:$('input[title=csrfmiddleware token]').val(),
            },
            success:function(data){
            alert(data);
            }

        });
    });
  
</script>
  

{% endblock content %}

posts/templates/posts/get_Posts.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>List of Live Data</h1>
<ul id="display-data">
  


</ul>
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
			  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
			  crossorigin="anonymous">

    console.log('Welcome to my list')          
    $(document).ready(function() {
        SetInterval(function(){
          $.ajax({
            type:'GET',
            url:"{% url 'posts:get_Posts' %}",
            success:function(response){
                 console.log(response);
                 $('#display').empty();
                for(var key in response. posts){
                var loop ,list ='<h2><li>' + response(posts[key].name) + '</li></h2>'
                $("#display").append(temp);
            };
            error:function$(response);{
              
              alert("An Error Occurred")
            };
        },
    },1000);

  });




});

</script>


{% endblock content %}

posts/templates/posts/posts_home.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> federalis Website {% block title %}Posts Home Page {% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/superhero/bootstrap.min.css">
       <link href="{% static 'giox/css/main.css' %}" rel="stylesheet" type="text/css">
       <link href="{% static 'giox/dashboard.css' %}" rel="styslesheet">
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    
  </head>
  <body>
    {% block content %}
  <div class="posts-container">
    <div class="posts-nav">
      <h1>Post-Navbar</h1><hr>
    <a class="posts-nav-a1" href="{% url 'posts:get_Posts' %}">Posts List</a><br>
    <a class="posts-nav-a2"   href= "{% url 'posts:create_posts' %}">Post</a><br>
    </div>
    <div class="posts-main">
      <div class="main-p">
      <h1>Thi is the The Post Page</h1><hr>
      </div>
      <div class="post-list">
        <h1>Posts-List</h1><hr>
      </div>
      <div class="post-graphics">
        <h1>Graphics</h1><hr>
      </div>
    </div>
    <div class="posts-footer">
      <p>@Posts-Foooter</p>
    </div>
  </div>

{%endblock content %}
    
    

    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
                    integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
                    crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
     
    <script src="" async defer></script>
  </body>
</html>


